config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
  get '/welcome', to: 'welcome#index'
  get 'cheat_codes', to: 'welcome#cheat_codes'
  get 'menu', to: 'welcome#menu'
  get 'order', to: 'welcome#order'
  get 'about', to: 'welcome#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= image_tag 'logo-and-title', class: "nav_img" %>
      <div class="toggle-button">
        <div class="stroke"></div>
      </div>
    </nav>
    <section class="dropdown hidden">
      <div><%= link_to 'Menu', menu_path %></div>
      <div><%= link_to 'Order', order_path %></div>
      <div><%= link_to 'About', about_path %></div>
      <div><%= link_to 'Cheat Codes', cheat_codes_path %></div>
    </section>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<section class="mobile">
  <h1>MoChew</h2>

  <div class="center">
    <h2>Coming Soon</h2>
    <button>Reserve an Order</button>
  </div>
</section>